activeEnvironment: lab

browser:
    browserInUse: chromium
    headlessMode: true
    fullscreenMode: true
    takeScreenshot: true
    webElementTimeout: 15
    webElementPooling: 10

environment:
  lab:
    envName: lab
    appUrl: https://www.selenium.dev
    title: Selenium
  prod:
    envName: prod
    appUrl: https://logback.qos.ch/
    title: Logback Home
